schema_version: 1

context:
  version: "1.0.5"

package:
  name: aiofastnet
  version: ${{ version }}

source:
  url: https://github.com/tarasko/aiofastnet/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 076ebe707c68c970c717dff68aba576e4ba35d59b8258acfee606a1628477080

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: match(python, "<3.11")

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - python
    - setuptools >=78.0
    - cython >=3.2
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - aiofastnet
      pip_check: true

about:
  summary: Fast transport/protocol networking for asyncio
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tarasko/aiofastnet
  repository: https://github.com/tarasko/aiofastnet

extra:
  recipe-maintainers:
    - thewchan
